import type { Producto } from "./datos-granjero";

export const VISITADORES = [
  "BOGDAN",
  "MARIA",
  "ALEIX",
  "SERGIO",
  "POL",
  "ALICIA",
  "JULIA",
  "JORGE",
  "JORDI",
  "LIVIU",
  "PAU",
  "VANESSA",
  "VALENTIN",
  "EDU",
];

export const MEDICAMENTOS_VISITADOR: Producto[] = [
  { nombre: "AMOXOIL RETARD 250ml", precio: 12.79 },
  { nombre: "CADOREX 300 mg/ml", precio: 15.20 },
  { nombre: "DFV DOXIVET 50 UNIDADES", precio: 4.24 },
  { nombre: "FLORTEK 100mg/ml (1L)", precio: 13.10 },
  { nombre: "LINALTEN", precio: 13.34 },
  { nombre: "LINCOSAN 800 MG/G", precio: 26.50 },
  { nombre: "LISMAY 150 GR", precio: 18.12 },
  { nombre: "MARBOCEN 250ml", precio: 26.00 },
  { nombre: "OCTACILLIN 1 KG", precio: 38.00 },
  { nombre: "OCTACILLIN 500 G", precio: 19.00 },
  { nombre: "PANVERMIN ORAL 1 KG", precio: 24.46 },
  { nombre: "PROBENCIL 300 mg/ml 250 ml", precio: 14.25 },
  { nombre: "RAPIDEXON 2 MG/ML", precio: 5.98 },
  { nombre: "SYVAQUINOL 10%", precio: 6.20 },
  { nombre: "TERMOVET", precio: 10.42 },
  { nombre: "SELECTAN 250 ML", precio: 12.88 },
  { nombre: "CLORVIOGEN", precio: 2.75 },
  { nombre: "FLOXAVEX", precio: 11.15 },
  { nombre: "AMOXIDIAN", precio: 9.66 },
  { nombre: "STELLAMUNE MYCOPLASMA 125 dosis", precio: 24.02 },
  { nombre: "AUSKIPRA", precio: 3.31 },
  { nombre: "DOXIVET 10 UNIDADES", precio: 4.39 },
];

export const MATERIALES_VISITADOR: Producto[] = [
  { nombre: "AGUJAS", precio: 1.43 },
  { nombre: "PAPEL MANOS", precio: 0 },
  { nombre: "BOLSAS PARA LOS PIES", precio: 1.24 },
  { nombre: "PAPEL BA\u00d1O", precio: 0 },
  { nombre: "TUBOS PARA SANGRAR", precio: 6.22 },
  { nombre: "SPRAY ROJO", precio: 2.38 },
  { nombre: "SPRAY AZUL", precio: 2.38 },
  { nombre: "BISTURIS", precio: 5.82 },
  { nombre: "GUANTES", precio: 1.95 },
  { nombre: "CAPUCHONES", precio: 0.04 },
  { nombre: "CROTALODOR CERDOS", precio: 12.97 },
  { nombre: "LAZO", precio: 11.07 },
  { nombre: "CROTALES", precio: 43.00 },
  { nombre: "ROTULADOR", precio: 5.50 },
  { nombre: "MUESTRAS DE AGUA", precio: 1.75 },
  { nombre: "PISTOLA MATAR", precio: 139.75 },
  { nombre: "BALAS", precio: 19.47 },
  { nombre: "JERINGA SERENA", precio: 161.94 },
  { nombre: "JERINGA HAUPTNER + ALARGADOR", precio: 38.95 },
  { nombre: "ACIDO FOSFORICO", precio: 0 },
  { nombre: "ACIDO ORGANICO", precio: 0 },
  { nombre: "DESINFECTANTE", precio: 0 },
  { nombre: "PEROXIDO", precio: 0 },
];
