import type { Producto } from "./datos-granjero";

export const VISITADORES = [
  "BOGDAN",
  "MARIA",
  "ALEIX",
  "SERGIO",
  "POL",
  "ALICIA",
  "JULIA",
  "JORGE",
  "JORDI",
  "LIVIU",
  "PAU",
  "VANESSA",
  "VALENTIN",
  "EDU",
];

export const MEDICAMENTOS_VISITADOR: Producto[] = [
  { nombre: "AMOXOIL RETARD 250ml" },
  { nombre: "CADOREX 300 mg/ml" },
  { nombre: "DFV DOXIVET 50 UNIDADES" },
  { nombre: "FLORTEK 100mg/ml (1L)" },
  { nombre: "LINALTEN" },
  { nombre: "LINCOSAN 800 MG/G" },
  { nombre: "LISMAY 150 GR" },
  { nombre: "MARBOCEN 250ml" },
  { nombre: "OCTACILLIN 1 KG" },
  { nombre: "OCTACILLIN 500 G" },
  { nombre: "PANVERMIN ORAL 1 KG" },
  { nombre: "PROBENCIL 300 mg/ml 250 ml" },
  { nombre: "RAPIDEXON 2 MG/ML" },
  { nombre: "SYVAQUINOL 10%" },
  { nombre: "TERMOVET" },
  { nombre: "SELECTAN 250 ML" },
  { nombre: "CLORVIOGEN" },
  { nombre: "FLOXAVEX" },
  { nombre: "AMOXIDIAN" },
  { nombre: "STELLAMUNE MYCOPLASMA 125 dosis" },
  { nombre: "AUSKIPRA" },
  { nombre: "DOXIVET 10 UNIDADES" },
];

export const MATERIALES_VISITADOR: Producto[] = [
  { nombre: "AGUJAS" },
  { nombre: "PAPEL MANOS" },
  { nombre: "BOLSAS PARA LOS PIES" },
  { nombre: "PAPEL BAÑO" },
  { nombre: "TUBOS PARA SANGRAR" },
  { nombre: "SPRAY ROJO" },
  { nombre: "SPRAY AZUL" },
  { nombre: "BISTURIS" },
  { nombre: "GUANTES" },
  { nombre: "CAPUCHONES" },
  { nombre: "CROTALODOR CERDOS" },
  { nombre: "LAZO" },
  { nombre: "CROTALES" },
  { nombre: "ROTULADOR" },
  { nombre: "MUESTRAS DE AGUA" },
  { nombre: "PISTOLA MATAR" },
  { nombre: "BALAS" },
  { nombre: "JERINGA SERENA" },
  { nombre: "JERINGA HAUPTNER + ALARGADOR" },
  { nombre: "ACIDO FOSFORICO" },
  { nombre: "ACIDO ORGANICO" },
  { nombre: "DESINFECTANTE" },
  { nombre: "PEROXIDO" },
];
