export type Producto = {
  nombre: string;
};

export const GRANJAS = [
  "Porcelibor",
  "Castellnou",
  "Pi",
  "Sisallar 1",
  "Senterada",
  "Sisallar 3",
  "Caserio",
  "Masia",
  "Granadella",
  "Fayon Abuela",
  "Industrial",
  "Cartuja 2",
  "Marrugat",
  "Sinoga",
  "Pascualet",
  "Noviporci",
  "Les Serres",
  "Alfuspi",
  "Fustero",
  "Guineu",
  "Santa Rosa",
  "Giralt",
  "El Soler",
  "Vendrell",
  "Pordall",
  "Rubio",
  "Escoda",
  "Cartuja 1",
  "Pordecona",
  "Sisallar 4",
  "Destete Zaidin",
  "Destete Jaumandreu",
  "Destete Maials",
  "Destete Borges 1",
];

export const MEDICAMENTOS_GRANJERO: Producto[] = [
  { nombre: "STELLAMUNE UNO" },
  { nombre: "STELLAMUNE MYCOPLASMA 125 dosis" },
  { nombre: "AUSKIPRA -GN 100 D" },
  { nombre: "SUISENG 50dosis" },
  { nombre: "CIRCO MAX MYCO 50 dosis" },
  { nombre: "AUTOV. COLI CLOST 100 ML" },
  { nombre: "AUTOV DISENTERE" },
  { nombre: "CIRCOFLEX" },
  { nombre: "CIRCOMAX MYCO 1VLX125DS" },
  { nombre: "ENZAPROST T" },
  { nombre: "ERYSENG PARVO 50d" },
  { nombre: "ERY+PARVO+LEPTO 50 ML -25 D" },
  { nombre: "GRIPORK 50d (100ml)" },
  { nombre: "INGELVAC PRRS EU FLEX 50 ml" },
  { nombre: "INGELVAC CIRCOFLEX 100 DS" },
  { nombre: "NEUMOSUIN 50 ds" },
  { nombre: "OVUCEL 25 dosis" },
  { nombre: "PORCILIS PRRS" },
  { nombre: "PORCICLIS LAWSONIA 100 dos." },
  { nombre: "PORCILIS PCV+MHYO 1*100 dosis" },
  { nombre: "PORCILIS PCV 50 dosis" },
  { nombre: "PORCILIS AR-T + DF 50 ML 25 D." },
  { nombre: "PORCILIS BEGONIA DF" },
  { nombre: "PORCILIS LAWSONIA" },
  { nombre: "PORCILIS ROTA 25 DOSIS" },
  { nombre: "PORCILIS COLICLOS 25 dosis" },
  { nombre: "PORCILIS PCV 100dosis" },
  { nombre: "PYRSVAC 183 500d (25*20)" },
  { nombre: "REPROCINE" },
  { nombre: "ReproCyc PRRS 100ML" },
  { nombre: "RHINISENG 50 dosis" },
  { nombre: "SINCROVALL 20 ml" },
  { nombre: "SUIPRAVAC PRRS 10 X 10" },
  { nombre: "SUVAXUN M.HYO 10X125 DS" },
  { nombre: "SUVAXYIN CIRCO 125 d." },
  { nombre: "SUVAXYIN PRRS 125 DS" },
  { nombre: "SYVA-BAX 250ml" },
  { nombre: "UNISTRAIN PRRS 50d" },
  { nombre: "VEPURED 250 D." },
  { nombre: "PORVAXIN ROTA+COLI+CLOS 50 ML 25 DS" },
  { nombre: "SUIPRAVAC PRRS 100ML" },
  { nombre: "EFICUR 100 ML" },
  { nombre: "TULADIAN 100 ML" },
  { nombre: "SUVAXYN MH-ONE 125 DS" },
  { nombre: "AMOXIDIAN" },
  { nombre: "AMOXOIL RETARD 250ml" },
  { nombre: "AMOXOIL RETARD 100 ml" },
  { nombre: "MEANIMELOXAN 20 mg/m" },
  { nombre: "CITRAMOX L.A. 150 mg" },
  { nombre: "COLIONE 5 Lts" },
  { nombre: "MECLORVIOGEN" },
  { nombre: "COCCIKLASS ORAL 1 L" },
  { nombre: "CADOREX 300 mg/ml" },
  { nombre: "CEFTIONIL 50mg/ml (250ml)" },
  { nombre: "CEFTIOMAX 50mg/ml (250ml)" },
  { nombre: "CENMETASONA 50ml" },
  { nombre: "CENMETASONA 100 ml" },
  { nombre: "COLIONE LAMONS" },
  { nombre: "CORDEXVALL 1,9 mg/ml 50 ml" },
  { nombre: "DEXABIOPEN 250ML" },
  { nombre: "DEXAFAST 100 ML" },
  { nombre: "DFV DOXIVET 500mg/g (100g)" },
  { nombre: "DRAXXIN 250 100 ML" },
  { nombre: "EFICUR 250ML" },
  { nombre: "EXABIOPEN 250 ML" },
  { nombre: "FLORTEK 100mg/ml (1L)" },
  { nombre: "GENTAMOX 100ML" },
  { nombre: "GENTAMOX 250 ML" },
  { nombre: "HEMO 141" },
  { nombre: "IVERCEN 10mg/ml" },
  { nombre: "KETOPROCEN 250 ML" },
  { nombre: "LINCOSAN 800 MG/G" },
  { nombre: "MARBOCEN 250ml" },
  { nombre: "MARBOCYL 2 % 250 ML" },
  { nombre: "MENBUTIL 100 mg/ml" },
  { nombre: "MONZAL" },
  { nombre: "NAXCEL PORCINO" },
  { nombre: "NEOMAY 1 KG" },
  { nombre: "PANVERMIN ORAL 1 KG" },
  { nombre: "PARACETAMOL SP" },
  { nombre: "PARTOVET 250 C.C" },
  { nombre: "PREVIRON 100ml" },
  { nombre: "PROBENCIL 300 mg/ml 250 ml" },
  { nombre: "RAPIDEXON 2 MG/ML 100 ML" },
  { nombre: "ROLAXIN 100 mg/ml" },
  { nombre: "SARNACURAN" },
  { nombre: "SELEVIT COMPLEX 100ml" },
  { nombre: "SINTEM 800 mg/ml" },
  { nombre: "SUACRON" },
  { nombre: "TERMOVET" },
  { nombre: "SYVAQUINOL 10%" },
  { nombre: "TULADIAN 100 mg/ml" },
  { nombre: "ZUPREVO" },
  { nombre: "ZUPREVO 40 MG/ML 100 ML" },
  { nombre: "SELECTAN 250 ML" },
];

export const MATERIALES_GRANJERO: Producto[] = [
  { nombre: "GASTRO K GEL" },
  { nombre: "JERINGA 20 ML" },
  { nombre: "JERINGA 10 ML" },
  { nombre: "BOMBILLAS 250 W" },
  { nombre: "BOMBILLAS 100 W" },
  { nombre: "PORTALAMPARAS" },
  { nombre: "PISTOLA SERENA COMPLETA + ALARGO + MOCHILAS" },
  { nombre: "PAPEL PARIDERA" },
  { nombre: "AGUJAS DESECHABLES 0.8*16 mm" },
  { nombre: "RECAMBIOS CORTACOLAS" },
  { nombre: "PAPEL DE MANOS" },
  { nombre: "CROTALES CERDAS MACHO" },
  { nombre: "CROTALES CERDAS HEMBRA" },
  { nombre: "TOALLAS HUMEDAS" },
  { nombre: "BOLSAS DE PIES" },
  { nombre: "AGUJAS 20X20" },
  { nombre: "AGUJAS 15X13" },
  { nombre: "AGUJAS 13X13" },
  { nombre: "AGUJAS 15X15" },
  { nombre: "AGUJAS 15X20" },
  { nombre: "AGUJAS 20X15" },
  { nombre: "AGUJAS 25X20" },
  { nombre: "AGUJAS 40X20" },
  { nombre: "AGUJAS 50X20" },
  { nombre: "AGUJAS 13X12" },
  { nombre: "AGUJAS 15X18" },
  { nombre: "AGUJAS 35X16" },
  { nombre: "AGUJAS 35X20" },
  { nombre: "AGUJAS 15X12" },
  { nombre: "AGUJAS 20X18" },
  { nombre: "BISTURIS N 22" },
  { nombre: "BISTURIS N 11" },
  { nombre: "BOTELLAS MUESTRA AGUA" },
  { nombre: "SPRAY VERDE" },
  { nombre: "SPRAY ROJO" },
  { nombre: "SPRAY AZUL" },
  { nombre: "VACUETTE 4.5 ml" },
  { nombre: "BOARMATE" },
  { nombre: "JERINGAS DE 20 ML" },
  { nombre: "JERINGAS DE 10 ML" },
  { nombre: "PAPEL BAÑO" },
  { nombre: "PISTOLA PARA MATAR" },
  { nombre: "GEL DUCHA" },
  { nombre: "FAIRY" },
  { nombre: "TOP MARKER AZUL" },
  { nombre: "TOP MARKER ROJO" },
  { nombre: "ALCOHOL 96" },
  { nombre: "JERINGA 1 ML" },
  { nombre: "JERINGA 2 ML" },
  { nombre: "PISTOLA HAUPTNER 50 ML" },
  { nombre: "PISTOLA HAUPTNER 25 ML" },
  { nombre: "CORTA-COLAS" },
  { nombre: "CUCHILLAS CORTA-COLAS" },
  { nombre: "LAPIZ TOP MARKER ROJO" },
  { nombre: "LAPIZ TOP MARKER AZUL" },
  { nombre: "ECOGRAFO" },
  { nombre: "BOLSAS DE BASURA" },
  { nombre: "GUANTES LATEX S" },
  { nombre: "GUANTES LATEX M" },
  { nombre: "GUANTES LATEX L" },
  { nombre: "GUANTES LATEX XL" },
  { nombre: "GUANTES VETERINARIOS" },
  { nombre: "HERBICIDA" },
  { nombre: "STAR DRAY PLUS 25 KG (SECANTE)" },
  { nombre: "STAR DETER ALCALIN (JABON SALAS) 25 KG" },
  { nombre: "STAR PEROX 220 KG / 25 KG" },
  { nombre: "STAR ACIDO FOSFORICO 25 KG / 240 KG" },
  { nombre: "OXYBAC GA 22 KG / 10 KG (DESINFECTANTE SALAS)" },
  { nombre: "STAR DIOX 75 A 160 LT" },
  { nombre: "STAR DIOX 75 B 20 LT" },
  { nombre: "STAR GERM GA 25 KG" },
  { nombre: "FECULA DE PATATA 25 KG" },
  { nombre: "STAR PEROX WATER 10 KG" },
  { nombre: "ALGIQUAT E-25 KG" },
  { nombre: "STAR DESIN ALBIDEN 5 KG / 25 KG" },
  { nombre: "HIPOCLORITO SODICO EN 901 25 KG / 240 KG" },
  { nombre: "MEDICADOR" },
  { nombre: "ACIDO ORTOFOSFORICO (ERMENGOL) 250 KG" },
  { nombre: "CLORO PRO A (ERMENGOL) 250 KG" },
  { nombre: "CLORO PRO 1 (ERMENGOL) 250 KG" },
  { nombre: "DEXTROSA 25 KG / 250 KG" },
  { nombre: "SULFATO DE HIERRO 25 KG" },
  { nombre: "DESINFECTANTE DE LOS PIES 25 KG" },
  { nombre: "DETERGENTE DE ROPA 10 KG" },
  { nombre: "SULFATO DE COBRE 25 KG" },
  { nombre: "LACTOINICIADOR 25 KG" },
  { nombre: "DENKAPIG MELLOW 15 KG" },
  { nombre: "DENKAPIG BABY WEAN 25KG" },
  { nombre: "DENKAPIG PREMIUM 25KG" },
  { nombre: "DENKAPIG LACTO START 25KG" },
  { nombre: "INTESTI-FORTE DIETETIC FEED 24 KG" },
  { nombre: "MATARATAS CEBO FRESCO" },
  { nombre: "MATARATAS BLOQUES" },
  { nombre: "MATARATAS GEL" },
  { nombre: "MATARATAS GRANULADO" },
  { nombre: "ACID VALL C4 20KG" },
  { nombre: "DETERGENTE LAVADORA" },
  { nombre: "DESINFECTANTE DE LOS PIES" },
  { nombre: "ANTIALGAS" },
];

export type RopaItem = {
  nombre: string;
  tallas?: string[];
};

const TALLAS_ROPA = ["S", "M", "L", "XL", "XXL"];
const TALLAS_ZAPATOS = ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46"];
const TALLAS_BOTAS = ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"];

export const ROPA_GRANJERO: RopaItem[] = [
  { nombre: "PANTALONES ROJOS", tallas: TALLAS_ROPA },
  { nombre: "PANTALONES ROSA", tallas: TALLAS_ROPA },
  { nombre: "CAMISETA MANGA CORTA", tallas: TALLAS_ROPA },
  { nombre: "CAMISETA MANGA LARGA", tallas: TALLAS_ROPA },
  { nombre: "SUDADERA", tallas: TALLAS_ROPA },
  { nombre: "ZAPATOS", tallas: TALLAS_ZAPATOS },
  { nombre: "BOTAS SEGURIDAD", tallas: TALLAS_BOTAS },
  { nombre: "CALCETINES" },
  { nombre: "TOALLAS" },
  { nombre: "CALZONCILLOS" },
  { nombre: "CASCO SEGURIDAD" },
  { nombre: "GAFAS SEGURIDAD" },
];
