export type Producto = {
  nombre: string;
  precio: number;
};

export const GRANJAS = [
  "Porcelibor",
  "Castellnou",
  "Pi",
  "Sisallar 1",
  "Senterada",
  "Sisallar 3",
  "Caserio",
  "Masia",
  "Granadella",
  "Fayon Abuela",
  "Industrial",
  "Cartuja 2",
  "Marrugat",
  "Sinoga",
  "Pascualet",
  "Noviporci",
  "Les Serres",
  "Alfuspi",
  "Fustero",
  "Guineu",
  "Santa Rosa",
  "Giralt",
  "El Soler",
  "Vendrell",
  "Pordall",
  "Rubio",
  "Escoda",
  "Cartuja 1",
  "Pordecona",
  "Sisallar 4",
  "Destete Zaidin",
  "Destete Jaumandreu",
  "Destete Maials",
  "Destete Borges 1",
];

export const MEDICAMENTOS_GRANJERO: Producto[] = [
  { nombre: "AMOXIDIAN", precio: 9.27 },
  { nombre: "AMOXOIL RETARD 250ml", precio: 12.79 },
  { nombre: "MEANIMELOXAN 20 mg/m", precio: 10.30 },
  { nombre: "CITRAMOX L.A. 150 mg", precio: 10.49 },
  { nombre: "COLIONE LAMONS", precio: 36.50 },
  { nombre: "MECLORVIOGEN", precio: 2.65 },
  { nombre: "COCCIKLASS ORAL 1 L", precio: 24.00 },
  { nombre: "DFV DOXIVET 500mg/g (100g)", precio: 4.24 },
  { nombre: "ERYSENG PARVO 50d", precio: 27.25 },
  { nombre: "ERY+PARVO+LEPTO 50 ML -25 D", precio: 66.69 },
  { nombre: "EXABIOPEN 250 ML", precio: 13.70 },
  { nombre: "FLORTEK 100mg/ml (1L)", precio: 13.10 },
  { nombre: "GRIPORK 50d (100ml)", precio: 16.96 },
  { nombre: "PCV 250 ML", precio: 87.13 },
  { nombre: "INGELVAC CIRCOFLEX 100 DS", precio: 90.00 },
  { nombre: "IVERTIN 500 ML", precio: 20.70 },
  { nombre: "LINALTEN", precio: 12.70 },
  { nombre: "LINCOSAN 800 MG/G", precio: 26.50 },
  { nombre: "LISMAY 150 GR", precio: 18.12 },
  { nombre: "MARBOSYVA 250 ML", precio: 30.40 },
  { nombre: "MARBOCEN 250ml", precio: 26.00 },
  { nombre: "MARBOCYL 2 %", precio: 21.70 },
  { nombre: "MENBUTIL 100 mg/ml", precio: 13.35 },
  { nombre: "MONZAL", precio: 33.10 },
  { nombre: "NAXCEL PORCINO", precio: 102.44 },
  { nombre: "NEOMAY 1 KG", precio: 22.28 },
  { nombre: "NEUMOSUIN 50 ds", precio: 13.70 },
  { nombre: "OVUCEL 25 dosis", precio: 57.49 },
  { nombre: "PANVERMIN ORAL 1 KG", precio: 24.46 },
  { nombre: "PARTOVET 250 C.C", precio: 5.85 },
  { nombre: "PORCILIS PRRS", precio: 72.16 },
  { nombre: "PORCICLIS LAWSONIA 100 dos.", precio: 123.30 },
  { nombre: "PORCILIS PCV+MHYO 1*100 dosis", precio: 105.54 },
  { nombre: "PORCILIS AR-T + DF 50 ML 25 D.", precio: 44.90 },
  { nombre: "PORCILIS ROTA 25 DOSIS", precio: 70.61 },
  { nombre: "PREVIRON 100ml", precio: 4.44 },
  { nombre: "PROBENCIL 300 mg/ml 250 ml", precio: 14.25 },
  { nombre: "MREPROCINE", precio: 47.85 },
  { nombre: "RHINISENG 50 dosis", precio: 63.29 },
  { nombre: "SELEVIT COMPLEX 100ml", precio: 12.56 },
  { nombre: "STELLAMUNE UNO", precio: 39.00 },
  { nombre: "STELLAMUNE MYCOPLASMA 125 dosis", precio: 19.38 },
  { nombre: "SUACRON", precio: 21.05 },
  { nombre: "SUISENG 50dosis", precio: 44.60 },
  { nombre: "SYVA-BAX 250ml", precio: 31.33 },
  { nombre: "SYVAQUINOL 10%", precio: 6.20 },
  { nombre: "TERMOVET", precio: 10.42 },
  { nombre: "VEPURED 250 D.", precio: 133.43 },
  { nombre: "VIRBAGEST 900 ml", precio: 43.18 },
  { nombre: "VIT-ESEL LAMONS", precio: 5.65 },
  { nombre: "ZUPREVO", precio: 86.80 },
  { nombre: "SELECTAN 250 ML", precio: 13.20 },
  { nombre: "PORVAXIN ROTA+COLI+CLOS 50 ML 25 DS", precio: 96.82 },
  { nombre: "ENZAPROST", precio: 20.75 },
  { nombre: "EFICUR 250 ML", precio: 17.80 },
  { nombre: "CADOREX", precio: 15.20 },
  { nombre: "RAPIDEXON 2 MG/ML", precio: 6.50 },
  { nombre: "VETDRAX 100 MG/ML", precio: 28.19 },
  { nombre: "ZURITOL", precio: 26.90 },
  { nombre: "VETRDAX", precio: 28.19 },
  { nombre: "FLOXAVEX", precio: 11.15 },
  { nombre: "OCTACILLIN", precio: 38.00 },
  { nombre: "DINOLYTIC", precio: 39.72 },
  { nombre: "VETRIMOXIN", precio: 16.38 },
  { nombre: "GENTAMOX", precio: 31.37 },
  { nombre: "HYDRABAS", precio: 3.75 },
];

export const MATERIALES_GRANJERO: Producto[] = [
  { nombre: "AGUJAS", precio: 1.39 },
  { nombre: "ALARGADOR HAUPTNER 41,57", precio: 39.90 },
  { nombre: "CRISTAL HAUPTNER 50 ML", precio: 1.70 },
  { nombre: "CRISTAL HAUPTNER 25 ML", precio: 1.78 },
  { nombre: "PISTOLA SACRIFICIO", precio: 149.80 },
  { nombre: "TOALLITA DESINFECTANTE", precio: 13.25 },
  { nombre: "JERINGA REVOLVER HAUPTNER 50 ML", precio: 39.00 },
  { nombre: "JERINGA REVOLVER HAUPTNER 25 ML", precio: 57.60 },
  { nombre: "JERINGA SERENA 5T CC CON ALARGADOR 40 CM", precio: 149.90 },
  { nombre: "JUEGO REPUESTOS SERENA 5 ML", precio: 0.95 },
  { nombre: "TENAZA ALLFLEX CERDAS", precio: 24.40 },
  { nombre: "TENAZA ALLFLEX LECHONES", precio: 8.30 },
  { nombre: "ROTULADOR ALLFLEX", precio: 5.55 },
  { nombre: "LAPIZ POT TOP MARKER", precio: 0.65 },
  { nombre: "BEBEDERO PARA TOLVA INBOX 98", precio: 2.50 },
  { nombre: "BOMBILLAS INFRARROJOS 250 W ROJA STANDARD", precio: 3.90 },
  { nombre: "CORTACOLAS RABOS ELECTRICO", precio: 82.60 },
  { nombre: "CORTA RABOS CON TRANSFORMADOR 750", precio: 82.60 },
  { nombre: "BOARMATE 250 ML", precio: 11.20 },
  { nombre: "TUBO VACUETTE 4,5 ML", precio: 6.25 },
  { nombre: "AGUJAS VACUTAINER 38/12", precio: 8.90 },
  { nombre: "BOTELLA RECOLECTORA DE AGUAS 500 ML", precio: 1.75 },
  { nombre: "BOTE PARA MUESTRAS 150ML", precio: 0.15 },
  { nombre: "LYC-TAG AMARILLO NUMERADO LECHONES", precio: 0.02 },
];

export function formatEur(value: number): string {
  return (
    value.toLocaleString("es-ES", {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }) + " \u20ac"
  );
}
